language: python

services:
  - docker

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker image build $IMAGE_NAME:$IMAGE_TAG .
  - docker push amenezes/$IMAGE_NAME:$IMAGE_TAG
  
env:
  global:
  - IMAGE_TAG=0.23.4
  - IMAGE_NAME=pandas
